package ca.diro.DataBase.Command;

public enum QueryCommand {
	CANCEL,COMING,COMMENT,LIST_PASSED,LIST_REGISTER,
	ADD, CLOSE_SESSION,CREATE_USER_ACCOUNT,DELETE,EDIT,
	LIST_CANCELLED,	OPEN_SESSION_EVENT,RESEARCH,SUBSCRIBE;
}
